# generated by datamodel-codegen:
#   filename:  openapi1.yaml
#   timestamp: 2025-10-30T12:39:23+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class Pet(BaseModel):
    pet_type: Annotated[str, Field(alias='petType')]


class Cat(Pet):
    name: str | None = None


class Dog(Pet):
    bark: str | None = None


class Lizard(Pet):
    loves_rocks: Annotated[bool | None, Field(alias='lovesRocks')] = None


class PetContainer(BaseModel):
    pet: Pet
