# generated by datamodel-codegen:
#   filename:  openapi4.yaml
#   timestamp: 2025-10-30T12:39:28+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field, RootModel


class Pet1(BaseModel):
    pass


class Cat(BaseModel):
    name: str | None = None


class Dog(BaseModel):
    bark: str | None = None


class Lizard(BaseModel):
    loves_rocks: Annotated[bool | None, Field(alias='lovesRocks')] = None


class Pet2(Cat, Pet1):
    pass


class Pet3(Dog, Pet1):
    pass


class Pet4(Lizard, Pet1):
    pass


class Pet(RootModel[Pet2 | Pet3 | Pet4]):
    root: Pet2 | Pet3 | Pet4


class PetContainer(BaseModel):
    pet: Pet
