# generated by datamodel-codegen:
#   filename:  openapi2.yaml
#   timestamp: 2025-10-30T12:39:25+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field, RootModel


class Cat(BaseModel):
    name: str | None = None


class Dog(BaseModel):
    bark: str | None = None


class Lizard(BaseModel):
    loves_rocks: Annotated[bool | None, Field(alias='lovesRocks')] = None


class Pet1(Cat):
    pet_type: Annotated[Literal['cat'], Field(alias='petType')]


class Pet2(Dog):
    pet_type: Annotated[Literal['dog'], Field(alias='petType')]


class Pet3(Lizard):
    pet_type: Annotated[Literal['lizard'], Field(alias='petType')]


class Pet(RootModel[Pet1 | Pet2 | Pet3]):
    root: Annotated[Pet1 | Pet2 | Pet3, Field(discriminator='pet_type')]


class PetContainer(BaseModel):
    pet: Pet
